apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::196549545232:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-JYTFVLLRVDMF
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::196549545232:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-04-15T17:07:56Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "3077"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 0582ec86-8592-434f-8744-2cd4f71a0967
